services:
  postgres:
    image: postgres:14-alpine
    container_name: league_api_db
    environment:
      POSTGRES_USER: league_user
      POSTGRES_PASSWORD: league_pass
      POSTGRES_DB: league_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U league_user -d league_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:14-alpine
    container_name: league_api_db_test
    environment:
      POSTGRES_USER: league_user
      POSTGRES_PASSWORD: league_pass
      POSTGRES_DB: league_db_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U league_user -d league_db_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  postgres_test_data:

